

<?php
/**
 * html code for tools tab
 */
$pro_plugins = array(
	0 => array(
		'title' => 'Advanced Shipment Tracking',
		'description' => 'Advanced Shipment Tracking comes with powerful features to help you manage & automate the WooCommerce fulfillment workflow.',
		'url' => 'https://www.zorem.com/product/woocommerce-advanced-shipment-tracking/',
		'image' => 'ast-icon.png',
		'file' => 'ast-pro/ast-pro.php'
	),
	1 => array(
		'title' => 'TrackShip for WooCommerce',
		'description' => 'Take control of your post-shipping workflows, reduce time spent on customer service and provide a superior post-purchase experience to your customers.Beyond automatic shipment tracking, TrackShip brings a branded tracking experience into your store, integrates into your workflow, and takes care of all the touch points with your customers after shipping.',
		'url' => 'https://wordpress.org/plugins/trackship-for-woocommerce/',
		'image' => 'trackship-logo.png',
		'file' => 'trackship-for-woocommerce/trackship-for-woocommerce.php'
	),
	2 => array(
		'title' => 'SMS For WooCommerce',
		'description' => 'Keep your customers informed by sending them automated SMS text messages with order & delivery updates. You can send SMS notifications to customers when the order status is updated or when the shipment is out for delivery and more…',
		'url' => 'https://www.zorem.com/product/sms-for-woocommerce/',
		'image' => 'smswoo-icon.png',
		'file' => 'sms-for-woocommerce/sms-for-woocommerce.php'
	),
	3 => array(
		'title' => 'Advanced Local Pickup',
		'description' => 'The Advanced Local Pickup (ALP) helps you manage the local pickup orders workflow more conveniently by extending the WooCommerce Local Pickup shipping method. The Pro you set up multiple pickup locations, , split the business hours, apply discounts by pickup location, display local pickup message on the products pages, allow customers to choose pickup location per product, force products to be local pickup only and more…',
		'url' => 'https://www.zorem.com/product/advanced-local-pickup-for-woocommerce/',
		'image' => 'alp.png',
		'file' => 'advanced-local-pickup-pro/advanced-local-pickup-pro.php'
	),	
	4 => array(
		'title' => ' Based Restrictions Pro',
		'description' => 'The country-based restrictions plugin by zorem works by the WooCommerce Geolocation or the shipping country added by the customer and allows you to restrict products on your store to sell or not to sell to specific countries.',
		'url' => 'https://www.zorem.com/product/country-based-restriction-pro/',
		'image' => 'cbr.png',
		'file' => 'country-base-restrictions-pro-addon/country-base-restrictions-pro-addon.php'
	),
	5 => array(
		'title' => 'Sales Report Email',
		'description' => 'The Sales Report Email Pro will help know how well your store is performing and how your products are selling by sending you a daily, weekly, or monthly sales report by email, directly from your WooCommerce store.',
		'url' => 'https://www.zorem.com/product/sales-report-email-pro/',
		'image' => 'sre.png',
		'file' => 'sales-report-email-pro/sales-report-email-pro.php'
	),
);

?>
<section id="alr_content2" class="alr_tab_section">
	<div class="d_table addons_page_dtable" style="">		
		<h3 class="sma_heading_addons_tab">WooCommerce plugins by zorem</h3>			
		
		<div class="plugins_section free_plugin_section">
			<?php foreach($pro_plugins as $plugin){ ?>
				<div class="single_plugin as-col-4">
					<div class="free_plugin_inner">
						<div class="paid_plugin_image">
							<img src="<?php echo Zorem_AJAX_Login_Register()->plugin_dir_url()?>assets/images/<?php echo $plugin['image']; ?>">
							<h3 class="plugin_title"><?php echo $plugin['title']; ?></h3>
						</div>
						<div class="paid_plugin_description">							
							<p><?php echo $plugin['description']; ?></p>
							<?php 
							if ( is_plugin_active( $plugin['file'] ) ) { ?>
								<button type="button" class="button button-disabled" disabled="disabled">Active</button>
							<?php } else{ ?>
								<a href="<?php echo $plugin['url']; ?>" class="install-now button-primary" target="blank">More Info</a>
							<?php } ?>								
						</div>
					</div>	
				</div>	
			<?php } ?>						
		</div>				
	</div>
</section>
